//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Settings/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""cb49e831-2293-41b1-9802-72e29edcf6f3"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""78507cad-4a0a-4553-b83e-ffa9affe5680"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Q"",
                    ""type"": ""Button"",
                    ""id"": ""3e5e6522-bf26-47f5-a137-ffe3a5b7daf9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""W"",
                    ""type"": ""Button"",
                    ""id"": ""ce8fdabe-e550-41cb-ab5d-35981135f1a4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E"",
                    ""type"": ""Button"",
                    ""id"": ""08b16753-869e-46e6-a746-a5fd9749d78a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R"",
                    ""type"": ""Button"",
                    ""id"": ""ae100d31-2669-47c1-a1c1-9170562d5195"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D"",
                    ""type"": ""Button"",
                    ""id"": ""666057cd-5c48-4e82-87fd-b7ab488c3a3b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F"",
                    ""type"": ""Button"",
                    ""id"": ""ea84cd5e-e921-4ec4-818c-6bb2bbaa60e0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""667a0608-5e50-4db3-9c7c-f1e1a6fcb5ae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""S"",
                    ""type"": ""Button"",
                    ""id"": ""2f848ecd-9fa1-4cfe-97df-416c03ce31b4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right_Mouse"",
                    ""type"": ""Button"",
                    ""id"": ""16b4b54b-ef35-4997-9e80-864564744578"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left_Mouse"",
                    ""type"": ""Button"",
                    ""id"": ""d810027d-2329-41cf-a137-36a32af77783"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camera_Change"",
                    ""type"": ""Button"",
                    ""id"": ""6c30fe70-1bc9-4425-8bf8-44cd73b07b97"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camera_Reset"",
                    ""type"": ""Button"",
                    ""id"": ""bbd5cef7-d505-46d8-b7e6-e016f7841eea"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Option"",
                    ""type"": ""Button"",
                    ""id"": ""bc1ea15e-fab8-4c27-9abe-21fb5802feb6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StoreKey"",
                    ""type"": ""Button"",
                    ""id"": ""2f1f9f36-298c-416f-ae83-c68602abfb24"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Recall"",
                    ""type"": ""Button"",
                    ""id"": ""08957b56-0216-4b90-8fc4-5f1e62e62d5d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Q Level Up"",
                    ""type"": ""Button"",
                    ""id"": ""ec861798-ab6b-4715-a463-fa5a2eb0e046"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""W Level Up"",
                    ""type"": ""Button"",
                    ""id"": ""bb056036-f581-4106-ac82-b47837ded1d6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E Level Up"",
                    ""type"": ""Button"",
                    ""id"": ""fc53271a-9f77-477b-b11b-4372a8b6e39f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R Level Up"",
                    ""type"": ""Button"",
                    ""id"": ""53e869e0-8d78-48f6-8e82-d58da917dacf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tab"",
                    ""type"": ""Button"",
                    ""id"": ""29d76f8f-58f6-4f15-a742-89f98c4f69a1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Equipment1"",
                    ""type"": ""Button"",
                    ""id"": ""9802c516-8c2f-46d8-b9d1-2e07cbfb6955"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Equipment2"",
                    ""type"": ""Button"",
                    ""id"": ""1b097caa-ab96-4f9d-b051-224cbf189b25"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Equipment3"",
                    ""type"": ""Button"",
                    ""id"": ""560a7987-1011-41e5-84d0-6611fef69779"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Equipment4"",
                    ""type"": ""Button"",
                    ""id"": ""5155c37a-c609-4a68-9cba-43456cc4f3f7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Equipment5"",
                    ""type"": ""Button"",
                    ""id"": ""837ec9f4-c5ae-4f47-8dab-353748e4bd7a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Equipment6"",
                    ""type"": ""Button"",
                    ""id"": ""845de536-df80-46f3-bc6b-24a7f00415e0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Animation1"",
                    ""type"": ""Button"",
                    ""id"": ""e420a24e-5411-472c-8801-b5bc47b0e78b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Animation2"",
                    ""type"": ""Button"",
                    ""id"": ""ff7f8892-bed8-4b85-9b3d-2e56bdd75c2f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Animation3"",
                    ""type"": ""Button"",
                    ""id"": ""f8ab74d2-05be-4fbc-b407-ec98eaba6d43"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Animation4"",
                    ""type"": ""Button"",
                    ""id"": ""fb5c0dfd-22fa-4b97-af50-a3a500d909bc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Animation5"",
                    ""type"": ""Button"",
                    ""id"": ""7ab08edf-5321-42ba-988a-bc552da06603"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Animation6"",
                    ""type"": ""Button"",
                    ""id"": ""136aee9c-c159-4f83-a4bc-6df885e35463"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9f50c553-58d7-4486-af24-f4bd20bc69cf"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70390658-fa4c-4d3a-89fc-f2f161e70fe9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Q"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0a4c821-f51e-47f9-94fc-1271be3848af"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""W"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ead8712c-c445-4b4d-8768-77637d0aed3f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""262e4b78-2046-414a-b73a-8e25a3ad0a8d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8598a89-ebbe-4ef9-988c-8e5f59b4be7e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Right_Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b6b3859-1a1a-4ade-be56-5bcdc5d624d0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Left_Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6759e65a-6dc8-49a9-ba24-3f3011030ae5"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Camera_Change"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7dc91d0-6d8b-4661-8a2f-0b9e90a39c37"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Camera_Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4728e900-d45a-4a5e-9f56-b95d74a8be5a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Option"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9084eb4e-c67b-4e1f-b187-ca3491354e06"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""StoreKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a4db47a-2f26-40b0-9641-0d77decde29c"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Recall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""7ab51633-3126-48da-829a-99ff34a050b2"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Q Level Up"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4d99baa7-b438-4826-8022-463857fa2fe4"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Q Level Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""2f4c6f6a-807c-47b5-a422-fceb5b463592"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Q Level Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""75504dd1-f1de-4828-82d9-dae6552f2770"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Animation1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9ace989a-f9d6-45a7-80fe-4596c22b15cb"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0095d911-8f20-409c-bbde-063a4caaef75"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""05542d81-01e7-4fc4-80ec-87f9bac4c545"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Animation2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""13f82600-d053-456c-b552-6ce2a118db81"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""75d0be6d-0f05-4e22-b23c-0ced51df5b6a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""a33c943e-3100-4b41-9f36-83c15961ae95"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Animation3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7db55ddf-73d2-49a6-9079-568536104ed1"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a3d4a273-0ce6-48e4-bca0-d7ee8c0b5f69"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""78e01284-a6ec-431e-b9dc-1de20ae2138e"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Animation4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""63d55507-f7fa-46ef-b7c4-07636a07fef8"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""26be9c17-0202-43dc-8d6e-4e7d8742eebb"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""6124fd47-7291-415b-bccc-81920ab52129"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Animation5"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d7586fd2-e21c-4abd-97e9-b31f20beead3"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""02a10366-5031-48de-9cd4-accbdc71be6b"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""0b5af672-cd5a-48d1-9ae6-d1838938c522"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Animation6"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""55526bbf-5b26-4f46-b7e9-40081b8c20bb"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""35c0ad20-ffce-40f2-adda-6e7ca381f575"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Animation6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""1caad774-2604-4044-80b9-f3d25941834c"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""W Level Up"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""3f0fffb1-ea1e-4522-ad24-c8a847ed909e"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""W Level Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""2f0eb57b-f271-4042-b538-18eb0064adc1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""W Level Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""6893034a-06ad-4d09-b39d-e0d2a1193c86"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E Level Up"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8dcca466-cfb1-4d24-8f53-3d560b2c4db3"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""E Level Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4cea380d-c674-4d17-9cc8-04e87a5183a4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""E Level Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""1b560419-2ea8-43e0-8fdc-77ecb93aca25"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R Level Up"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""618371cc-124e-49c3-9551-b4339e7ccaae"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""R Level Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""4c4a6e1a-4191-44b9-a06d-196be9efc9a4"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""R Level Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b58a7099-5fab-4169-8610-889d7ebe379f"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Tab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d2e3bbf-947c-4665-9c7b-e8ce28a7a6a7"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Equipment1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67ff8279-3be7-4baf-a62f-126a27eb1ed4"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Equipment2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb95209c-dcca-46ee-adf0-21be09cd2479"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Equipment3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26593b02-a5e0-443d-a49c-70844bc7f393"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Equipment4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62b11ecc-16e4-4d29-857a-abbd3b13817c"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Equipment5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a22ae92-898a-4481-8820-3987b9cea158"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""Equipment6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6bca91e-bc4b-4fe8-aefd-feaefa14439c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d6ac559-3a62-4657-9651-541e27416244"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f6daf38-eb85-4c53-ab42-746f5db165a0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c977c24-79f1-4748-ba0f-c25427543b8a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoard and Mouse"",
                    ""action"": ""S"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyBoard and Mouse"",
            ""bindingGroup"": ""KeyBoard and Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_MousePosition = m_Player.FindAction("MousePosition", throwIfNotFound: true);
        m_Player_Q = m_Player.FindAction("Q", throwIfNotFound: true);
        m_Player_W = m_Player.FindAction("W", throwIfNotFound: true);
        m_Player_E = m_Player.FindAction("E", throwIfNotFound: true);
        m_Player_R = m_Player.FindAction("R", throwIfNotFound: true);
        m_Player_D = m_Player.FindAction("D", throwIfNotFound: true);
        m_Player_F = m_Player.FindAction("F", throwIfNotFound: true);
        m_Player_A = m_Player.FindAction("A", throwIfNotFound: true);
        m_Player_S = m_Player.FindAction("S", throwIfNotFound: true);
        m_Player_Right_Mouse = m_Player.FindAction("Right_Mouse", throwIfNotFound: true);
        m_Player_Left_Mouse = m_Player.FindAction("Left_Mouse", throwIfNotFound: true);
        m_Player_Camera_Change = m_Player.FindAction("Camera_Change", throwIfNotFound: true);
        m_Player_Camera_Reset = m_Player.FindAction("Camera_Reset", throwIfNotFound: true);
        m_Player_Option = m_Player.FindAction("Option", throwIfNotFound: true);
        m_Player_StoreKey = m_Player.FindAction("StoreKey", throwIfNotFound: true);
        m_Player_Recall = m_Player.FindAction("Recall", throwIfNotFound: true);
        m_Player_QLevelUp = m_Player.FindAction("Q Level Up", throwIfNotFound: true);
        m_Player_WLevelUp = m_Player.FindAction("W Level Up", throwIfNotFound: true);
        m_Player_ELevelUp = m_Player.FindAction("E Level Up", throwIfNotFound: true);
        m_Player_RLevelUp = m_Player.FindAction("R Level Up", throwIfNotFound: true);
        m_Player_Tab = m_Player.FindAction("Tab", throwIfNotFound: true);
        m_Player_Equipment1 = m_Player.FindAction("Equipment1", throwIfNotFound: true);
        m_Player_Equipment2 = m_Player.FindAction("Equipment2", throwIfNotFound: true);
        m_Player_Equipment3 = m_Player.FindAction("Equipment3", throwIfNotFound: true);
        m_Player_Equipment4 = m_Player.FindAction("Equipment4", throwIfNotFound: true);
        m_Player_Equipment5 = m_Player.FindAction("Equipment5", throwIfNotFound: true);
        m_Player_Equipment6 = m_Player.FindAction("Equipment6", throwIfNotFound: true);
        m_Player_Animation1 = m_Player.FindAction("Animation1", throwIfNotFound: true);
        m_Player_Animation2 = m_Player.FindAction("Animation2", throwIfNotFound: true);
        m_Player_Animation3 = m_Player.FindAction("Animation3", throwIfNotFound: true);
        m_Player_Animation4 = m_Player.FindAction("Animation4", throwIfNotFound: true);
        m_Player_Animation5 = m_Player.FindAction("Animation5", throwIfNotFound: true);
        m_Player_Animation6 = m_Player.FindAction("Animation6", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerInputActions.Player.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_MousePosition;
    private readonly InputAction m_Player_Q;
    private readonly InputAction m_Player_W;
    private readonly InputAction m_Player_E;
    private readonly InputAction m_Player_R;
    private readonly InputAction m_Player_D;
    private readonly InputAction m_Player_F;
    private readonly InputAction m_Player_A;
    private readonly InputAction m_Player_S;
    private readonly InputAction m_Player_Right_Mouse;
    private readonly InputAction m_Player_Left_Mouse;
    private readonly InputAction m_Player_Camera_Change;
    private readonly InputAction m_Player_Camera_Reset;
    private readonly InputAction m_Player_Option;
    private readonly InputAction m_Player_StoreKey;
    private readonly InputAction m_Player_Recall;
    private readonly InputAction m_Player_QLevelUp;
    private readonly InputAction m_Player_WLevelUp;
    private readonly InputAction m_Player_ELevelUp;
    private readonly InputAction m_Player_RLevelUp;
    private readonly InputAction m_Player_Tab;
    private readonly InputAction m_Player_Equipment1;
    private readonly InputAction m_Player_Equipment2;
    private readonly InputAction m_Player_Equipment3;
    private readonly InputAction m_Player_Equipment4;
    private readonly InputAction m_Player_Equipment5;
    private readonly InputAction m_Player_Equipment6;
    private readonly InputAction m_Player_Animation1;
    private readonly InputAction m_Player_Animation2;
    private readonly InputAction m_Player_Animation3;
    private readonly InputAction m_Player_Animation4;
    private readonly InputAction m_Player_Animation5;
    private readonly InputAction m_Player_Animation6;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePosition => m_Wrapper.m_Player_MousePosition;
        public InputAction @Q => m_Wrapper.m_Player_Q;
        public InputAction @W => m_Wrapper.m_Player_W;
        public InputAction @E => m_Wrapper.m_Player_E;
        public InputAction @R => m_Wrapper.m_Player_R;
        public InputAction @D => m_Wrapper.m_Player_D;
        public InputAction @F => m_Wrapper.m_Player_F;
        public InputAction @A => m_Wrapper.m_Player_A;
        public InputAction @S => m_Wrapper.m_Player_S;
        public InputAction @Right_Mouse => m_Wrapper.m_Player_Right_Mouse;
        public InputAction @Left_Mouse => m_Wrapper.m_Player_Left_Mouse;
        public InputAction @Camera_Change => m_Wrapper.m_Player_Camera_Change;
        public InputAction @Camera_Reset => m_Wrapper.m_Player_Camera_Reset;
        public InputAction @Option => m_Wrapper.m_Player_Option;
        public InputAction @StoreKey => m_Wrapper.m_Player_StoreKey;
        public InputAction @Recall => m_Wrapper.m_Player_Recall;
        public InputAction @QLevelUp => m_Wrapper.m_Player_QLevelUp;
        public InputAction @WLevelUp => m_Wrapper.m_Player_WLevelUp;
        public InputAction @ELevelUp => m_Wrapper.m_Player_ELevelUp;
        public InputAction @RLevelUp => m_Wrapper.m_Player_RLevelUp;
        public InputAction @Tab => m_Wrapper.m_Player_Tab;
        public InputAction @Equipment1 => m_Wrapper.m_Player_Equipment1;
        public InputAction @Equipment2 => m_Wrapper.m_Player_Equipment2;
        public InputAction @Equipment3 => m_Wrapper.m_Player_Equipment3;
        public InputAction @Equipment4 => m_Wrapper.m_Player_Equipment4;
        public InputAction @Equipment5 => m_Wrapper.m_Player_Equipment5;
        public InputAction @Equipment6 => m_Wrapper.m_Player_Equipment6;
        public InputAction @Animation1 => m_Wrapper.m_Player_Animation1;
        public InputAction @Animation2 => m_Wrapper.m_Player_Animation2;
        public InputAction @Animation3 => m_Wrapper.m_Player_Animation3;
        public InputAction @Animation4 => m_Wrapper.m_Player_Animation4;
        public InputAction @Animation5 => m_Wrapper.m_Player_Animation5;
        public InputAction @Animation6 => m_Wrapper.m_Player_Animation6;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @Q.started += instance.OnQ;
            @Q.performed += instance.OnQ;
            @Q.canceled += instance.OnQ;
            @W.started += instance.OnW;
            @W.performed += instance.OnW;
            @W.canceled += instance.OnW;
            @E.started += instance.OnE;
            @E.performed += instance.OnE;
            @E.canceled += instance.OnE;
            @R.started += instance.OnR;
            @R.performed += instance.OnR;
            @R.canceled += instance.OnR;
            @D.started += instance.OnD;
            @D.performed += instance.OnD;
            @D.canceled += instance.OnD;
            @F.started += instance.OnF;
            @F.performed += instance.OnF;
            @F.canceled += instance.OnF;
            @A.started += instance.OnA;
            @A.performed += instance.OnA;
            @A.canceled += instance.OnA;
            @S.started += instance.OnS;
            @S.performed += instance.OnS;
            @S.canceled += instance.OnS;
            @Right_Mouse.started += instance.OnRight_Mouse;
            @Right_Mouse.performed += instance.OnRight_Mouse;
            @Right_Mouse.canceled += instance.OnRight_Mouse;
            @Left_Mouse.started += instance.OnLeft_Mouse;
            @Left_Mouse.performed += instance.OnLeft_Mouse;
            @Left_Mouse.canceled += instance.OnLeft_Mouse;
            @Camera_Change.started += instance.OnCamera_Change;
            @Camera_Change.performed += instance.OnCamera_Change;
            @Camera_Change.canceled += instance.OnCamera_Change;
            @Camera_Reset.started += instance.OnCamera_Reset;
            @Camera_Reset.performed += instance.OnCamera_Reset;
            @Camera_Reset.canceled += instance.OnCamera_Reset;
            @Option.started += instance.OnOption;
            @Option.performed += instance.OnOption;
            @Option.canceled += instance.OnOption;
            @StoreKey.started += instance.OnStoreKey;
            @StoreKey.performed += instance.OnStoreKey;
            @StoreKey.canceled += instance.OnStoreKey;
            @Recall.started += instance.OnRecall;
            @Recall.performed += instance.OnRecall;
            @Recall.canceled += instance.OnRecall;
            @QLevelUp.started += instance.OnQLevelUp;
            @QLevelUp.performed += instance.OnQLevelUp;
            @QLevelUp.canceled += instance.OnQLevelUp;
            @WLevelUp.started += instance.OnWLevelUp;
            @WLevelUp.performed += instance.OnWLevelUp;
            @WLevelUp.canceled += instance.OnWLevelUp;
            @ELevelUp.started += instance.OnELevelUp;
            @ELevelUp.performed += instance.OnELevelUp;
            @ELevelUp.canceled += instance.OnELevelUp;
            @RLevelUp.started += instance.OnRLevelUp;
            @RLevelUp.performed += instance.OnRLevelUp;
            @RLevelUp.canceled += instance.OnRLevelUp;
            @Tab.started += instance.OnTab;
            @Tab.performed += instance.OnTab;
            @Tab.canceled += instance.OnTab;
            @Equipment1.started += instance.OnEquipment1;
            @Equipment1.performed += instance.OnEquipment1;
            @Equipment1.canceled += instance.OnEquipment1;
            @Equipment2.started += instance.OnEquipment2;
            @Equipment2.performed += instance.OnEquipment2;
            @Equipment2.canceled += instance.OnEquipment2;
            @Equipment3.started += instance.OnEquipment3;
            @Equipment3.performed += instance.OnEquipment3;
            @Equipment3.canceled += instance.OnEquipment3;
            @Equipment4.started += instance.OnEquipment4;
            @Equipment4.performed += instance.OnEquipment4;
            @Equipment4.canceled += instance.OnEquipment4;
            @Equipment5.started += instance.OnEquipment5;
            @Equipment5.performed += instance.OnEquipment5;
            @Equipment5.canceled += instance.OnEquipment5;
            @Equipment6.started += instance.OnEquipment6;
            @Equipment6.performed += instance.OnEquipment6;
            @Equipment6.canceled += instance.OnEquipment6;
            @Animation1.started += instance.OnAnimation1;
            @Animation1.performed += instance.OnAnimation1;
            @Animation1.canceled += instance.OnAnimation1;
            @Animation2.started += instance.OnAnimation2;
            @Animation2.performed += instance.OnAnimation2;
            @Animation2.canceled += instance.OnAnimation2;
            @Animation3.started += instance.OnAnimation3;
            @Animation3.performed += instance.OnAnimation3;
            @Animation3.canceled += instance.OnAnimation3;
            @Animation4.started += instance.OnAnimation4;
            @Animation4.performed += instance.OnAnimation4;
            @Animation4.canceled += instance.OnAnimation4;
            @Animation5.started += instance.OnAnimation5;
            @Animation5.performed += instance.OnAnimation5;
            @Animation5.canceled += instance.OnAnimation5;
            @Animation6.started += instance.OnAnimation6;
            @Animation6.performed += instance.OnAnimation6;
            @Animation6.canceled += instance.OnAnimation6;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @Q.started -= instance.OnQ;
            @Q.performed -= instance.OnQ;
            @Q.canceled -= instance.OnQ;
            @W.started -= instance.OnW;
            @W.performed -= instance.OnW;
            @W.canceled -= instance.OnW;
            @E.started -= instance.OnE;
            @E.performed -= instance.OnE;
            @E.canceled -= instance.OnE;
            @R.started -= instance.OnR;
            @R.performed -= instance.OnR;
            @R.canceled -= instance.OnR;
            @D.started -= instance.OnD;
            @D.performed -= instance.OnD;
            @D.canceled -= instance.OnD;
            @F.started -= instance.OnF;
            @F.performed -= instance.OnF;
            @F.canceled -= instance.OnF;
            @A.started -= instance.OnA;
            @A.performed -= instance.OnA;
            @A.canceled -= instance.OnA;
            @S.started -= instance.OnS;
            @S.performed -= instance.OnS;
            @S.canceled -= instance.OnS;
            @Right_Mouse.started -= instance.OnRight_Mouse;
            @Right_Mouse.performed -= instance.OnRight_Mouse;
            @Right_Mouse.canceled -= instance.OnRight_Mouse;
            @Left_Mouse.started -= instance.OnLeft_Mouse;
            @Left_Mouse.performed -= instance.OnLeft_Mouse;
            @Left_Mouse.canceled -= instance.OnLeft_Mouse;
            @Camera_Change.started -= instance.OnCamera_Change;
            @Camera_Change.performed -= instance.OnCamera_Change;
            @Camera_Change.canceled -= instance.OnCamera_Change;
            @Camera_Reset.started -= instance.OnCamera_Reset;
            @Camera_Reset.performed -= instance.OnCamera_Reset;
            @Camera_Reset.canceled -= instance.OnCamera_Reset;
            @Option.started -= instance.OnOption;
            @Option.performed -= instance.OnOption;
            @Option.canceled -= instance.OnOption;
            @StoreKey.started -= instance.OnStoreKey;
            @StoreKey.performed -= instance.OnStoreKey;
            @StoreKey.canceled -= instance.OnStoreKey;
            @Recall.started -= instance.OnRecall;
            @Recall.performed -= instance.OnRecall;
            @Recall.canceled -= instance.OnRecall;
            @QLevelUp.started -= instance.OnQLevelUp;
            @QLevelUp.performed -= instance.OnQLevelUp;
            @QLevelUp.canceled -= instance.OnQLevelUp;
            @WLevelUp.started -= instance.OnWLevelUp;
            @WLevelUp.performed -= instance.OnWLevelUp;
            @WLevelUp.canceled -= instance.OnWLevelUp;
            @ELevelUp.started -= instance.OnELevelUp;
            @ELevelUp.performed -= instance.OnELevelUp;
            @ELevelUp.canceled -= instance.OnELevelUp;
            @RLevelUp.started -= instance.OnRLevelUp;
            @RLevelUp.performed -= instance.OnRLevelUp;
            @RLevelUp.canceled -= instance.OnRLevelUp;
            @Tab.started -= instance.OnTab;
            @Tab.performed -= instance.OnTab;
            @Tab.canceled -= instance.OnTab;
            @Equipment1.started -= instance.OnEquipment1;
            @Equipment1.performed -= instance.OnEquipment1;
            @Equipment1.canceled -= instance.OnEquipment1;
            @Equipment2.started -= instance.OnEquipment2;
            @Equipment2.performed -= instance.OnEquipment2;
            @Equipment2.canceled -= instance.OnEquipment2;
            @Equipment3.started -= instance.OnEquipment3;
            @Equipment3.performed -= instance.OnEquipment3;
            @Equipment3.canceled -= instance.OnEquipment3;
            @Equipment4.started -= instance.OnEquipment4;
            @Equipment4.performed -= instance.OnEquipment4;
            @Equipment4.canceled -= instance.OnEquipment4;
            @Equipment5.started -= instance.OnEquipment5;
            @Equipment5.performed -= instance.OnEquipment5;
            @Equipment5.canceled -= instance.OnEquipment5;
            @Equipment6.started -= instance.OnEquipment6;
            @Equipment6.performed -= instance.OnEquipment6;
            @Equipment6.canceled -= instance.OnEquipment6;
            @Animation1.started -= instance.OnAnimation1;
            @Animation1.performed -= instance.OnAnimation1;
            @Animation1.canceled -= instance.OnAnimation1;
            @Animation2.started -= instance.OnAnimation2;
            @Animation2.performed -= instance.OnAnimation2;
            @Animation2.canceled -= instance.OnAnimation2;
            @Animation3.started -= instance.OnAnimation3;
            @Animation3.performed -= instance.OnAnimation3;
            @Animation3.canceled -= instance.OnAnimation3;
            @Animation4.started -= instance.OnAnimation4;
            @Animation4.performed -= instance.OnAnimation4;
            @Animation4.canceled -= instance.OnAnimation4;
            @Animation5.started -= instance.OnAnimation5;
            @Animation5.performed -= instance.OnAnimation5;
            @Animation5.canceled -= instance.OnAnimation5;
            @Animation6.started -= instance.OnAnimation6;
            @Animation6.performed -= instance.OnAnimation6;
            @Animation6.canceled -= instance.OnAnimation6;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KeyBoardandMouseSchemeIndex = -1;
    public InputControlScheme KeyBoardandMouseScheme
    {
        get
        {
            if (m_KeyBoardandMouseSchemeIndex == -1) m_KeyBoardandMouseSchemeIndex = asset.FindControlSchemeIndex("KeyBoard and Mouse");
            return asset.controlSchemes[m_KeyBoardandMouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
        void OnQ(InputAction.CallbackContext context);
        void OnW(InputAction.CallbackContext context);
        void OnE(InputAction.CallbackContext context);
        void OnR(InputAction.CallbackContext context);
        void OnD(InputAction.CallbackContext context);
        void OnF(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnS(InputAction.CallbackContext context);
        void OnRight_Mouse(InputAction.CallbackContext context);
        void OnLeft_Mouse(InputAction.CallbackContext context);
        void OnCamera_Change(InputAction.CallbackContext context);
        void OnCamera_Reset(InputAction.CallbackContext context);
        void OnOption(InputAction.CallbackContext context);
        void OnStoreKey(InputAction.CallbackContext context);
        void OnRecall(InputAction.CallbackContext context);
        void OnQLevelUp(InputAction.CallbackContext context);
        void OnWLevelUp(InputAction.CallbackContext context);
        void OnELevelUp(InputAction.CallbackContext context);
        void OnRLevelUp(InputAction.CallbackContext context);
        void OnTab(InputAction.CallbackContext context);
        void OnEquipment1(InputAction.CallbackContext context);
        void OnEquipment2(InputAction.CallbackContext context);
        void OnEquipment3(InputAction.CallbackContext context);
        void OnEquipment4(InputAction.CallbackContext context);
        void OnEquipment5(InputAction.CallbackContext context);
        void OnEquipment6(InputAction.CallbackContext context);
        void OnAnimation1(InputAction.CallbackContext context);
        void OnAnimation2(InputAction.CallbackContext context);
        void OnAnimation3(InputAction.CallbackContext context);
        void OnAnimation4(InputAction.CallbackContext context);
        void OnAnimation5(InputAction.CallbackContext context);
        void OnAnimation6(InputAction.CallbackContext context);
    }
}
